# Netlify configuration
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  publish = "dist/"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
