name: Build
on: push
jobs:
  build:
    name: Test and build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-10.15
          - windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup node environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Unit test
        run: npm run test
      - name: Build artifacts
        run: npm run build
